publicKey:
  primary: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJKj79jAkcVeV5AMESHVJt0QkCQAOhCyJJKHQtww3RSfmlFd4jIkHjuGTBx8kNYK4sttAJH0STUUD9HG0as8OccCAwEAAQ==

spring:
  datasource:
    primary:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.2.113:3306/jh_rep_v2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: OglXcbGQNyalsfSAhOwpndnAf3M6aaD6xTgtDnN85QSoBtO3Pu7vnev8aHVTxP7Apip1NZ8M8A4ggxaP5LJwvA==
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # stat与wall的顺序影响到拦截检测的时间是否在StatFilter统计的SQL执行时间内
      filters: stat,wall,config
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        reset-enable: false
        url-pattern: '/druid/*'

      # 配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      # 获取连接等待超时时间
      maxWait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      # 一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # druid.stat.mergeSql-SQL合并配置；druid.stat.slowSqlMillis-慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000;config.decrypt=true;config.decrypt.key=${publicKey.primary}

    back:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.2.113:3306/jh_vue?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: 123456Ab
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙;
      # stat与wall的顺序影响到拦截检测的时间是否在StatFilter统计的SQL执行时间内
      filters: stat,wall,log4j
      # 配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      # 获取连接等待超时时间
      maxWait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      # 一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # druid.stat.mergeSql-SQL合并配置；druid.stat.slowSqlMillis-慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000

#是否启用接口文档 是 true 否 false
swagger2:
  enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*/*.xml
  typeAliasesPackage: com.sy.model.*.*

logging:
  config: classpath:config/logback-dev.xml